# Numpy Array Creation

In [1]:
import numpy as np

In [2]:
a = [1,2,3]
a= np.array(a)
print(a)

[1 2 3]


In [3]:
a = [1,2,3]
a = np.array([a,a])
print(a)

[[1 2 3]
 [1 2 3]]


In [4]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

# Access Array : Indexing, Slicing , Iterating , Filtering

In [5]:
import numpy as np

arr = np.array([[10, 20, 30, 40, 50],
                [60, 70, 80, 90, 100],
                [110, 120, 130, 140, 150]])

print("Original Array:")
print(arr)

# Indexing
print("\nIndexing:")
print(f"Element at (0, 0): {arr[0, 0]}")
print(f"Element at (1, 3): {arr[1, 3]}")

# Slicing
print("\nSlicing:")
print("First row, all columns: ", arr[0, :])
print("All rows, second column: ", arr[:, 1])
print("Rows 0 to 1, columns 2 to 4: ", arr[0:2, 2:5])

# Iterating
print("\nIterating:")
print("Iterating through rows:")
for row in arr:
    print(row)

print("Iterating through elements:")
for element in arr.flat:
    print(element, end=' ')
print()

# Filtering (Boolean Indexing)
print("\nFiltering:")
filter_condition = arr > 100
print("Elements greater than 100 (boolean mask): ")
print(filter_condition)
print("Filtered elements: ", arr[filter_condition])

print("Elements equal to 80: ", arr[arr == 80])

Original Array:
[[ 10  20  30  40  50]
 [ 60  70  80  90 100]
 [110 120 130 140 150]]

Indexing:
Element at (0, 0): 10
Element at (1, 3): 90

Slicing:
First row, all columns:  [10 20 30 40 50]
All rows, second column:  [ 20  70 120]
Rows 0 to 1, columns 2 to 4:  [[ 30  40  50]
 [ 80  90 100]]

Iterating:
Iterating through rows:
[10 20 30 40 50]
[ 60  70  80  90 100]
[110 120 130 140 150]
Iterating through elements:
10 20 30 40 50 60 70 80 90 100 110 120 130 140 150 

Filtering:
Elements greater than 100 (boolean mask): 
[[False False False False False]
 [False False False False False]
 [ True  True  True  True  True]]
Filtered elements:  [110 120 130 140 150]
Elements equal to 80:  [80]


# Array Basic Operation

In [6]:
# Create sample arrays for demonstration
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])
arr3 = np.array([[1, 2], [3, 4]])
arr4 = np.array([[5, 6], [7, 8]])

print("Array 1:", arr1)
print("Array 2:", arr2)
print("Array 3:\n", arr3)
print("Array 4:\n", arr4)

# --- Arithmetic Operations ---
print("\n--- Arithmetic Operations ---")
print("Addition (arr1 + arr2):", arr1 + arr2)
print("Subtraction (arr1 - arr2):", arr1 - arr2)
print("Multiplication (arr1 * arr2):", arr1 * arr2) # Element-wise multiplication
print("Division (arr1 / arr2):", arr1 / arr2)
print("Scalar multiplication (arr1 * 2):", arr1 * 2)
print("Dot product (arr3 @ arr4):\n", arr3 @ arr4) # Matrix multiplication

# --- Universal Functions (ufuncs) ---
print("\n--- Universal Functions (ufuncs) ---")
print("Square root (np.sqrt(arr1)):", np.sqrt(arr1))
print("Exponential (np.exp(arr1)):", np.exp(arr1))
print("Sine (np.sin(arr1)):", np.sin(arr1))

# --- Aggregation Functions ---
print("\n--- Aggregation Functions ---")
print("Sum of arr1 (np.sum(arr1)):", np.sum(arr1))
print("Min of arr1 (np.min(arr1)):", np.min(arr1))
print("Max of arr1 (np.max(arr1)):", np.max(arr1))
print("Mean of arr1 (np.mean(arr1)):", np.mean(arr1))
print("Standard Deviation of arr1 (np.std(arr1)):", np.std(arr1))

# Aggregations on 2D arrays (axis parameter)
print("\nSum of arr3 (all elements):", np.sum(arr3))
print("Sum of arr3 along rows (axis=0):", np.sum(arr3, axis=0)) # Sum columns
print("Sum of arr3 along columns (axis=1):", np.sum(arr3, axis=1)) # Sum rows

Array 1: [1 2 3 4 5]
Array 2: [ 6  7  8  9 10]
Array 3:
 [[1 2]
 [3 4]]
Array 4:
 [[5 6]
 [7 8]]

--- Arithmetic Operations ---
Addition (arr1 + arr2): [ 7  9 11 13 15]
Subtraction (arr1 - arr2): [-5 -5 -5 -5 -5]
Multiplication (arr1 * arr2): [ 6 14 24 36 50]
Division (arr1 / arr2): [0.16666667 0.28571429 0.375      0.44444444 0.5       ]
Scalar multiplication (arr1 * 2): [ 2  4  6  8 10]
Dot product (arr3 @ arr4):
 [[19 22]
 [43 50]]

--- Universal Functions (ufuncs) ---
Square root (np.sqrt(arr1)): [1.         1.41421356 1.73205081 2.         2.23606798]
Exponential (np.exp(arr1)): [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
Sine (np.sin(arr1)): [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]

--- Aggregation Functions ---
Sum of arr1 (np.sum(arr1)): 15
Min of arr1 (np.min(arr1)): 1
Max of arr1 (np.max(arr1)): 5
Mean of arr1 (np.mean(arr1)): 3.0
Standard Deviation of arr1 (np.std(arr1)): 1.4142135623730951

Sum of arr3 (all elements): 10
Sum of ar

# Numpy Array Concatenation

In [7]:
#1D array

a= np.array([1,2,3])
b= np.array([4,5,6])
c= np.concatenate((a,b))
print(c)

[1 2 3 4 5 6]


In [10]:
#2D array

a= np.array([[1,2,3],[4,5,6]])
b= np.array([[7,8,9],[10,11,12]])

print(np.vstack([a,b]))
print(np.hstack((a,b)))

for element in np.nditer(a):
    print(element)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
1
2
3
4
5
6


# Linear Algebra operation

In [11]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5,6],[7,8]])

# Matrix

In [14]:
#multiplication

print(A@B)
print(np.dot(A,B))

#transpose

print (A.T)

#determination

print(np.linalg.det(A))

#inverse

print(np.linalg.inv(A))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[1 3]
 [2 4]]
-2.0000000000000004
[[-2.   1. ]
 [ 1.5 -0.5]]
