# Basic operation

In [1]:
import numpy as np

In [2]:
A = np.array([
    [2,-1,3],
    [4,0,7],
    [-2,1,8]])
B = np.array([[3,7,-9],[5,7,9],[1,-6,8]])

In [3]:
print(A+B)

[[ 5  6 -6]
 [ 9  7 16]
 [-1 -5 16]]


In [4]:
print(A-B)

[[-1 -8 12]
 [-1 -7 -2]
 [-3  7  0]]


In [5]:
print(np.dot(A,B))  #numpay library dot function call

[[  4 -11  -3]
 [ 19 -14  20]
 [  7 -55  91]]


In [6]:
print(A@B)  #dot

[[  4 -11  -3]
 [ 19 -14  20]
 [  7 -55  91]]


# Cross product

In [ ]:
A = np.array([
    [2,-1,3],
    [4,0,7],
    [-2,1,8]])
B = np.array([[3,7,-9],[5,7,9],[1,-6,8]])

# COLUM wise

In [11]:
cross_cols = []

for i in range(1) :
  a= A[:,i]
  b= B[:,i]
  print(np.cross(a,b))



[14 -8 -2]


In [7]:
cross_cols = []

for i in range(3) :
  a= A[:,i]
  b= B[:,i]
  cross_cols.append(np.cross(a,b))

cross_cols = np.array(cross_cols)
cross_cols

array([[ 14,  -8,  -2],
       [ -7,   1,  -7],
       [-16, -96,  90]])

# Row wise

In [13]:
cross_result =[]

for i in range(3) :
  a= A[i]
  b= B[i]
  cross_result.append(np.cross(a,b))

cross_result = np.array(cross_result)
cross_result


array([[-12,  27,  17],
       [-49,  -1,  28],
       [ 56,  24,  11]])

# Inverse Calculation

In [17]:
A = np.array([
    [2,-1,3],
    [4,0,7],
    [-2,1,8]])
print(A)

[[ 2 -1  3]
 [ 4  0  7]
 [-2  1  8]]


# Determinate

In [18]:
det_A = np.linalg.det(A)
det_A

np.float64(44.000000000000014)

# Cofactor

In [29]:
def cofactor_matrix(M):
  M = np.array(M)
  n = M.shape[0]
  # Initialize C with float64 dtype to preserve precision and avoid truncation errors
  C = np.zeros((n, n), dtype=np.float64)

  for i in range(n):
    for j in range(n):
      # Create the submatrix by deleting the i-th row and j-th column
      sub_M = np.delete(np.delete(M, i, axis=0), j, axis=1)
      # Calculate the determinant of the submatrix
      det_sub_M = np.linalg.det(sub_M)
      # Calculate the cofactor
      cofactor = ((-1)**(i + j)) * det_sub_M
      C[i, j] = cofactor
  return C

### What is a Cofactor Matrix?

The **cofactor matrix** of a square matrix `M` is a matrix of the same dimensions where each element `C_ij` is the cofactor of the corresponding element `M_ij` in the original matrix.

The cofactor `C_ij` is calculated as:

`C_ij = (-1)^(i+j) * det(M_ij)`

Where:
- `i` is the row index and `j` is the column index.
- `det(M_ij)` is the determinant of the **minor** matrix `M_ij`, which is the submatrix formed by removing the i-th row and j-th column from the original matrix `M`.

In [25]:
# Calculate the cofactor matrix for A
cofactor_A = cofactor_matrix(A)
print("Cofactor matrix of A:")
print(cofactor_A)

Cofactor matrix of A:
[[ -6 -46   4]
 [ 11  22   0]
 [ -6  -2   4]]


### What is an Adjoint Matrix?

The **adjoint matrix** (also known as the **adjugate matrix**) of a square matrix `A` is the transpose of its cofactor matrix. It is denoted as `adj(A)` or `A_adj`.

`adj(A) = (Cof(A))^T`

Where `Cof(A)` is the cofactor matrix of `A`, and `T` denotes the transpose operation.

The adjoint matrix is particularly useful in finding the inverse of a matrix using the formula:

`A⁻¹ = (1 / det(A)) * adj(A)`

In [26]:
# Calculate the adjoint matrix by transposing the cofactor matrix
adjoint_A = cofactor_A.T
print("Adjoint matrix of A:")
print(adjoint_A)

Adjoint matrix of A:
[[ -6  11  -6]
 [-46  22  -2]
 [  4   0   4]]


### Inverse using Determinant and Adjoint

We can also calculate the inverse of a matrix using the formula:

`A⁻¹ = (1 / det(A)) * adj(A)`

Let's apply this formula using the `det_A` and `adjoint_A` we've already computed.

In [27]:
# Calculate the inverse using the formula: A_inv = (1 / det_A) * adjoint_A
inverse_from_formula = (1 / det_A) * adjoint_A

print("Inverse of A calculated using formula (1/det(A)) * adj(A):")
print(inverse_from_formula)

Inverse of A calculated using formula (1/det(A)) * adj(A):
[[-0.13636364  0.25       -0.13636364]
 [-1.04545455  0.5        -0.04545455]
 [ 0.09090909  0.          0.09090909]]


### Comparison with `np.linalg.inv()`

Let's compare this result with the direct calculation using `np.linalg.inv()` to ensure consistency.

In [28]:
# Calculate the inverse directly using numpy for comparison
inverse_from_numpy = np.linalg.inv(A)

print("Inverse of A calculated directly using np.linalg.inv():")
print(inverse_from_numpy)

# Check if the two results are approximately equal
print("\nAre the two inverse calculations approximately equal?")
print(np.allclose(inverse_from_formula, inverse_from_numpy))

Inverse of A calculated directly using np.linalg.inv():
[[-0.15909091  0.25       -0.15909091]
 [-1.04545455  0.5        -0.04545455]
 [ 0.09090909  0.          0.09090909]]

Are the two inverse calculations approximately equal?
False
